Refactor types
wavesplatform/signer pull request #21
Opened 2020-02-28 11:18 UTC by mrpq

2020-02-28 11:24 UTC, mrpq commented on src/types/api.ts
> +          // ? TInvokeScriptTransaction
TS ругается на слишком большую вложенность если добавит еще хоть 1 свичкейс, приходится извлекать этот конкретный кейс отсюда (см ниже)

2020-02-29 21:01 UTC, finico commented on package.json
> +    "save-dev": "0.0.1-security"
WAT?

2020-03-03 09:02 UTC, tsigel requested changes

2020-03-03 09:02 UTC, tsigel commented on package.json
> +  "main": "dist/cjs/src/index.js",
Убрать `src`

2020-03-03 09:02 UTC, tsigel commented on package.json
> +    "bundle:d": "cross-env NODE_ENV=development webpack",
Сделать таск на компиляцию типов и убрать их из гита. Добавить это в prepublish.

2020-03-03 09:02 UTC, tsigel commented on src/types/index.ts
> +export type IssueArgs = CommonArgs &
Давай сделаем читабельнее.

2020-03-06 08:41 UTC, tsigel commented on src/types/api.ts
> +
Добавить в гитигнор и генерировать.

2020-03-10 13:51 UTC, tsigel approved these changes

2020-03-10 13:54 UTC, merged